<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="wwwroot\node_modules\echarts-liquidfill\example\fill-container.html" />
    <Content Include="wwwroot\node_modules\echarts-liquidfill\example\index.html" />
    <Content Include="wwwroot\node_modules\echarts-liquidfill\example\test.html" />
    <Content Include="wwwroot\node_modules\echarts-liquidfill\package.json" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\node_modules\echarts-liquidfill\dist\echarts-liquidfill.js" />
    <None Include="wwwroot\node_modules\echarts-liquidfill\dist\echarts-liquidfill.min.js" />
    <None Include="wwwroot\node_modules\echarts-liquidfill\dist\echarts-liquidfill.min.js.map" />
    <None Include="wwwroot\node_modules\echarts-liquidfill\dist\echarts.js" />
    <None Include="wwwroot\node_modules\echarts-liquidfill\index.js" />
    <None Include="wwwroot\node_modules\echarts-liquidfill\license.md" />
    <None Include="wwwroot\node_modules\echarts-liquidfill\README.md" />
    <None Include="wwwroot\node_modules\echarts-liquidfill\src\liquidFill.js" />
    <None Include="wwwroot\node_modules\echarts-liquidfill\src\liquidFillLayout.js" />
    <None Include="wwwroot\node_modules\echarts-liquidfill\src\liquidFillSeries.js" />
  </ItemGroup>

</Project>
